import json
import os
from pathlib import Path
from datetime import date

from openai import OpenAI
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from dotenv import load_dotenv

load_dotenv()

CLIENT = OpenAI(
    api_key=os.environ.get("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1",
)

OUTPUT_DIR = Path(__file__).parent / "output"

SLIDE_PLAN_PROMPT = """\
You are a presentation architect. Given source excerpts and a user topic, \
produce a JSON slide deck plan.

Return ONLY valid JSON (no markdown fences) with this structure:
{
  "title": "Presentation title",
  "subtitle": "One-line subtitle",
  "slides": [
    {
      "heading": "Slide heading",
      "bullets": ["Point 1 [Source N]", "Point 2 [Source N]"],
      "notes": "Optional speaker notes"
    }
  ],
  "sources": [
    {"number": 1, "title": "Source title", "url": "https://..."}
  ]
}

Rules:
- 4-8 content slides (not counting title and sources slides).
- Each bullet must cite its source as [Source N].
- Keep bullets concise (≤ 20 words each).
- Group related information into thematic slides.
- Do NOT invent facts. Use ONLY the provided sources.
- If sources are insufficient, include a slide noting the gaps.
- End with a sources list matching every [Source N] cited."""


BRAND = {
    "bg": RGBColor(0x0F, 0x17, 0x2A),
    "accent": RGBColor(0x38, 0xBD, 0xF8),
    "text": RGBColor(0xF1, 0xF5, 0xF9),
    "muted": RGBColor(0x94, 0xA3, 0xB8),
    "bullet_highlight": RGBColor(0x38, 0xBD, 0xF8),
}


def _plan_slides(topic: str, context: str) -> dict:
    messages = [
        {"role": "system", "content": SLIDE_PLAN_PROMPT},
        {
            "role": "user",
            "content": f"Sources:\n\n{context}\n\n---\n\nTopic: {topic}",
        },
    ]
    resp = CLIENT.chat.completions.create(
        model="llama-3.1-8b-instant",
        max_tokens=2048,
        messages=messages,
        temperature=0.3,
    )
    raw = resp.choices[0].message.content.strip()
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1]
        raw = raw.rsplit("```", 1)[0]
    return json.loads(raw)


def _set_slide_bg(slide, color: RGBColor):
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_textbox(slide, left, top, width, height, text, font_size, color,
                 bold=False, alignment=PP_ALIGN.LEFT):
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(font_size)
    p.font.color.rgb = color
    p.font.bold = bold
    p.alignment = alignment
    return tf


def _build_title_slide(prs, plan):
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
    _set_slide_bg(slide, BRAND["bg"])

    _add_textbox(
        slide,
        Inches(0.8), Inches(1.8), Inches(8.4), Inches(1.5),
        plan["title"],
        36, BRAND["text"], bold=True, alignment=PP_ALIGN.LEFT,
    )

    _add_textbox(
        slide,
        Inches(0.8), Inches(3.3), Inches(8.4), Inches(0.8),
        plan.get("subtitle", ""),
        18, BRAND["muted"], alignment=PP_ALIGN.LEFT,
    )

    _add_textbox(
        slide,
        Inches(0.8), Inches(4.5), Inches(8.4), Inches(0.5),
        f"Generated by LEXI  ·  {date.today().isoformat()}",
        12, BRAND["muted"], alignment=PP_ALIGN.LEFT,
    )

    accent_bar = slide.shapes.add_shape(
        1, Inches(0.8), Inches(3.15), Inches(2), Pt(3),
    )
    accent_bar.fill.solid()
    accent_bar.fill.fore_color.rgb = BRAND["accent"]
    accent_bar.line.fill.background()


def _build_content_slide(prs, slide_data):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, BRAND["bg"])

    _add_textbox(
        slide,
        Inches(0.8), Inches(0.5), Inches(8.4), Inches(0.8),
        slide_data["heading"],
        28, BRAND["accent"], bold=True,
    )

    accent_bar = slide.shapes.add_shape(
        1, Inches(0.8), Inches(1.2), Inches(1.5), Pt(2),
    )
    accent_bar.fill.solid()
    accent_bar.fill.fore_color.rgb = BRAND["accent"]
    accent_bar.line.fill.background()

    txBox = slide.shapes.add_textbox(
        Inches(0.8), Inches(1.5), Inches(8.4), Inches(5.0),
    )
    tf = txBox.text_frame
    tf.word_wrap = True

    for i, bullet in enumerate(slide_data.get("bullets", [])):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.space_after = Pt(10)
        p.space_before = Pt(4)

        marker = p.add_run()
        marker.text = "▸  "
        marker.font.size = Pt(14)
        marker.font.color.rgb = BRAND["accent"]

        run = p.add_run()
        run.text = bullet
        run.font.size = Pt(14)
        run.font.color.rgb = BRAND["text"]

    notes = slide_data.get("notes", "")
    if notes:
        slide.notes_slide.notes_text_frame.text = notes


def _build_sources_slide(prs, sources):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, BRAND["bg"])

    _add_textbox(
        slide,
        Inches(0.8), Inches(0.5), Inches(8.4), Inches(0.8),
        "Sources",
        28, BRAND["accent"], bold=True,
    )

    txBox = slide.shapes.add_textbox(
        Inches(0.8), Inches(1.5), Inches(8.4), Inches(5.0),
    )
    tf = txBox.text_frame
    tf.word_wrap = True

    for i, src in enumerate(sources):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.space_after = Pt(6)

        num_run = p.add_run()
        num_run.text = f"[{src['number']}]  "
        num_run.font.size = Pt(12)
        num_run.font.color.rgb = BRAND["accent"]
        num_run.font.bold = True

        title_run = p.add_run()
        title_run.text = src.get("title", "Untitled")
        title_run.font.size = Pt(12)
        title_run.font.color.rgb = BRAND["text"]

        url = src.get("url", "")
        if url:
            url_run = p.add_run()
            url_run.text = f"\n      {url}"
            url_run.font.size = Pt(10)
            url_run.font.color.rgb = BRAND["muted"]


def generate_pptx(topic: str, context: str) -> Path:
    plan = _plan_slides(topic, context)

    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(5.625)  # 16:9

    _build_title_slide(prs, plan)

    for slide_data in plan.get("slides", []):
        _build_content_slide(prs, slide_data)

    if plan.get("sources"):
        _build_sources_slide(prs, plan["sources"])

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    safe_name = "".join(c if c.isalnum() or c in " _-" else "" for c in topic)[:60].strip()
    filename = f"{safe_name}.pptx"
    out_path = OUTPUT_DIR / filename
    prs.save(str(out_path))
    return out_path
